### ISSUE TITLE
Thanks & Omni-rig version

### ISSUE THREAD

**Issue by vgegok** [michalin/easysdr#1]
I am trying to build your magical project, and the PCB and components are already on the way. I suggest that you modify the download address of Omni-rig in README.md to the latest version (screenshot of your HDSDR settings). HDSDR V2.80+ supports Omni-rig V2.1 or newer versions:
[https://www.hb9ryz.ch/omnirig/](https://www.hb9ryz.ch/omnirig/)
Once again, this is really a great project, and I believe I can learn a lot through your project.

There seems to be a problem with my sound card. When I am not connected to the easysdr board:
There will be a very high peak in LO!
![image](https://github.com/michalin/easysdr/assets/45798060/7ddba3af-9de6-4285-8a0f-b8f78a41af2f)

**Comment by michalin** [comment]
Link in Readme changed.
